<?php

namespace SeoThemes\GenesisCodeSnippets;

/**
 * Class Admin
 *
 * @package SeoThemes\GenesisCodeSnippets
 */
class Admin extends Plugin {

	/**
	 * Run admin hooks.
	 *
	 * @since 1.0.0
	 *
	 * @return void
	 */
	public function run() {
		if ( ! current_user_can( 'manage_options' ) ) {
			return;
		}

		add_action( 'admin_init', [ $this, 'write_to_file' ] );
		add_action( 'admin_enqueue_scripts', [ $this, 'enqueue_assets' ] );
		add_filter( 'plugin_action_links_' . plugin_basename( $this->file ), [ $this, 'add_action_links' ] );
	}

	/**
	 * Load admin scripts and styles.
	 *
	 * @since 1.0.0
	 *
	 * @return void
	 */
	public function enqueue_assets() {
		wp_enqueue_code_editor( [
			'type'       => 'text/x-php',
			'codemirror' => [
				'scrollbarStyle' => 'null',
			],
		] );
		wp_enqueue_script(
			$this->prefix( 'admin' ),
			$this->url . 'assets/scripts.js', [ 'jquery' ]
		);
		wp_enqueue_style(
			$this->prefix( 'admin' ),
			$this->url . 'assets/styles.css'
		);
	}

	/**
	 * Generate static files.
	 *
	 * @since 1.0.0
	 *
	 * @uses  \WP_Filesystem()
	 *
	 * @return void
	 */
	public function write_to_file() {
		include_once ABSPATH . 'wp-admin/includes/file.php';
		\WP_Filesystem();
		global $wp_filesystem;
		wp_mkdir_p( $this->cache );

		foreach ( $this->types as $type ) {
			$file = $this->cache . $this->handle . '.' . $type;
			$code = $this->{$type};
			$cred = "\n/* " . __( 'Generated by ', 'genesis-code-snippets' ) . $this->name . " */";

			// Skip if code has not changed.
			if ( $wp_filesystem->get_contents( $file ) === $code ) {
				continue;
			}

			// Add opening PHP tag.
			if ( 'php' === $type ) {
				$code = "<?php\n" . $code;
			}

			// Wrap JS code in jQuery function.
			if ( 'js' === $type ) {
				$code = 'jQuery(function ($) {' . $code . '});';
			}

			$wp_filesystem->put_contents( $file, $code . "\n" . $cred );
		}
	}

	/**
	 * Add settings link to plugins list.
	 *
	 * @since 1.0.0
	 *
	 * @param $links
	 *
	 * @return array
	 */
	public function add_action_links( $links ) {
		return array_merge( $links, [
			sprintf(
				'<a href="%s">%s</a>',
				admin_url( 'admin.php?page=' . $this->handle ),
				__( 'Settings', 'genesis-code-snippets' ) ),
		] );
	}
}
