<?php

namespace SeoThemes\GenesisCodeSnippets;

class Admin {

	/**
	 * @var Plugin
	 */
	private $plugin;

	public $temp;

	/**
	 * Admin constructor.
	 *
	 * @param Plugin $plugin Plugin instance.
	 */
	public function __construct( $plugin ) {
		$this->plugin = $plugin;
	}

	/**
	 * Description of expected behavior.
	 *
	 * @since 1.0.0
	 *
	 * @return void
	 */
	public function run() {
		add_action( 'admin_init', [ $this, 'write_to_file' ], 11 );
		add_action( 'admin_enqueue_scripts', [ $this, 'enqueue_scripts' ] );
		add_filter( 'plugin_action_links_' . plugin_basename( $this->plugin->file ), [ $this, 'add_action_links' ] );
	}

	/**
	 * Description of expected behavior.
	 *
	 * @since 1.0.0
	 *
	 * @param $hook
	 *
	 * @return void
	 */
	public function enqueue_scripts( $hook ) {
		wp_enqueue_code_editor( [
			'type'       => 'text/x-php',
			'codemirror' => [
				'scrollbarStyle' => 'null',
			],
		] );
		wp_enqueue_script(
			$this->plugin->handle . '-admin',
			$this->plugin->url . 'assets/scripts.js', [ 'jquery' ]
		);
		wp_enqueue_style(
			$this->plugin->handle . '-admin',
			$this->plugin->url . 'assets/styles.css'
		);
	}

	/**
	 * Description of expected behavior.
	 *
	 * @since 1.0.0
	 *
	 * @param $links
	 *
	 * @return array
	 */
	public function add_action_links( $links ) {
		return array_merge( $links, [
			sprintf(
				'<a href="%s">%s</a>',
				admin_url( 'admin.php?page=' . $this->plugin->handle ),
				__( 'Settings', 'genesis-code-snippets' ) ),
		] );
	}

	/**
	 * Generate static file.
	 *
	 * @since 1.0.0
	 *
	 * @uses  \WP_Filesystem()
	 *
	 * @return void
	 */
	public function write_to_file() {
		include_once ABSPATH . 'wp-admin/includes/file.php';
		\WP_Filesystem();
		global $wp_filesystem;
		wp_mkdir_p( $this->plugin->cache );

		foreach ( $this->plugin->types as $type ) {
			$file = $this->plugin->cache . $this->plugin->handle . '.' . $type;
			$code = $this->plugin->{$type};
			$cred = "\n/* " . __( 'Generated by ', 'genesis-code-snippets' ) . $this->plugin->name . " */";

			if ( $wp_filesystem->get_contents( $file ) === $code ) {
				continue;
			}

			if ( 'php' === $type ) {
				$code = "<?php\n" . $code;
			}

			if ( 'js' === $type ) {
				$code = 'jQuery(function ($) {' . $code . '});';
			}

			$wp_filesystem->put_contents( $file, $code . "\n" . $cred );
		}
	}
}
